"""5  revision

Revision ID: 0c60bed39d39
Revises: 9a1fd80b6a08
Create Date: 2023-09-03 13:57:56.397764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c60bed39d39'
down_revision = '9a1fd80b6a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
