"""Second revision

Revision ID: 384464ff36b3
Revises: a3dff9b39002
Create Date: 2023-09-02 10:17:19.035528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384464ff36b3'
down_revision = 'a3dff9b39002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('foodType', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_type'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('food')
    op.drop_table('admins')
    # ### end Alembic commands ###
