"""Third  revision

Revision ID: 698b030c8fd5
Revises: 384464ff36b3
Create Date: 2023-09-02 10:24:32.503859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698b030c8fd5'
down_revision = '384464ff36b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'foodType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('foodType', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
