"""4  revision

Revision ID: 9a1fd80b6a08
Revises: 698b030c8fd5
Create Date: 2023-09-02 11:03:00.181385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1fd80b6a08'
down_revision = '698b030c8fd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
